- name: Ensure gpg is installed
  apt:
    name: gnupg
    state: present
    
- name: Create directory for Cloudflare GPG key
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Add Cloudflare GPG key
  ansible.builtin.shell: |
    curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

- name: Add Cloudflare apt repository
  ansible.builtin.shell: |
    echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared focal main' | tee /etc/apt/sources.list.d/cloudflared.list

- name: Update apt package index
  apt:
    update_cache: yes

- name: Install Cloudflared
  apt:
    name: cloudflared
    state: present