- name: Install Wireguard 
  apt:
    name: wireguard-tools
    state: present

- name: Ensure udp2raw directory exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/udp2raw
    - /etc/udp2raw

- name: Get udp2raw binary package
  unarchive:
    src: "https://github.com/wangyu-/udp2raw/releases/download/{{ udp2raw_ver }}/udp2raw_binaries.tar.gz"
    dest: /opt/udp2raw
    remote_src: yes

- name: Symlink binary of udp2raw
  file:
    src: "/opt/udp2raw/udp2raw_amd64"
    dest: "/usr/local/bin/udp2raw"
    state: link