- name: Update and Upgrade 
  hosts: all
  become: yes
  become_method: sudo # use sudo to escalate privileges
  vars_files:
    - group_vars/all.yaml
  roles:
    - basic

- name: Configure sysctl settings
  hosts: 
    - transit
    - node_server
  become: yes
  become_method: sudo # use sudo to escalate privileges
  vars_files:
    - group_vars/all.yaml
  roles:
    - network-optimize