- name: Transit Server Configuration
  hosts: 
    - transit
    - node_server
  become: yes
  become_method: sudo # use sudo to escalate privileges
  vars_files:
    - group_vars/all.yaml
  roles:
    - transit